// Command neoma-discover scans Go packages for error usage and generates a Go
// source file that registers discovered errors for OpenAPI documentation.
//
// The tool finds the ErrorHandler assignment in the module, reads its NewError
// method to determine the concrete error type, then scans all handlers for
// references to that type (struct literals, function calls returning it,
// variables of that type). If no handler is found, it falls back to scanning
// all loaded packages for a type that implements StatusCode() int.
//
// Usage:
//
//	//go:generate go run github.com/MeGaNeKoS/neoma/cmd/neoma-discover -output neoma_errors_gen.go ./...
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"

	"golang.org/x/tools/go/packages"
)

type discoveredError struct {
	Status int
	Title  string
	Detail string
}

type errorTypeInfo struct {
	PkgPath  string
	TypeName string
}

type handlerTypeInfo struct {
	PkgPath  string
	TypeName string
	rawType  types.Type
}

func main() {
	output := flag.String("output", "neoma_errors_gen.go", "output file name")
	flag.Parse()

	patterns := flag.Args()
	if len(patterns) == 0 {
		patterns = []string{"./..."}
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedImports |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedDeps,
	}

	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		log.Fatalf("failed to load packages: %v", err)
	}

	allPkgs := map[string]*packages.Package{}
	for _, pkg := range pkgs {
		collectPackages(pkg, allPkgs)
	}

	handlerInfo := findHandlerType(pkgs)
	var errType *errorTypeInfo

	if handlerInfo != nil {
		errType = findNewErrorReturnType(handlerInfo.rawType, allPkgs)
		if errType != nil {
			fmt.Printf("neoma-discover: found error type %s.%s from handler %s\n",
				errType.PkgPath, errType.TypeName, handlerInfo.TypeName)
		}
	}

	if errType == nil {
		errType = findStatusCodeType(allPkgs)
		if errType != nil {
			fmt.Printf("neoma-discover: found error type %s.%s via StatusCode() method\n",
				errType.PkgPath, errType.TypeName)
		}
	}

	if errType == nil {
		fmt.Println("neoma-discover: could not determine error type, nothing to discover")
		return
	}

	statusField := findStatusFieldName(errType, allPkgs)
	fmt.Printf("neoma-discover: using status field %q\n", statusField)

	for _, pkg := range pkgs {
		result := map[string][]discoveredError{}

		for _, file := range pkg.Syntax {
			ast.Inspect(file, func(n ast.Node) bool {
				fn, ok := n.(*ast.FuncDecl)
				if !ok {
					return true
				}
				if fn.Name == nil || !fn.Name.IsExported() {
					return true
				}

				visited := map[string]bool{}
				errs := discoverErrors(pkg, fn.Body, allPkgs, visited, errType, statusField)
				if len(errs) > 0 {
					result[fn.Name.Name] = dedup(errs)
				}

				for _, w := range detectRemappedErrors(fn.Name.Name, pkg, fn.Body, allPkgs, errType, statusField) {
					fmt.Println(w)
				}

				return true
			})
		}

		if len(result) == 0 {
			continue
		}

		generated := generateFile(pkg.Name, result)

		outPath := *output
		if filepath.Dir(*output) == "." && len(pkg.GoFiles) > 0 {
			outPath = filepath.Join(filepath.Dir(pkg.GoFiles[0]), *output)
		}
		if err := os.WriteFile(outPath, generated, 0644); err != nil {
			log.Fatalf("failed to write %s: %v", outPath, err)
		}
		fmt.Printf("neoma-discover: wrote %s (%d handlers)\n", outPath, len(result))
	}
}

func collectPackages(pkg *packages.Package, m map[string]*packages.Package) {
	if _, ok := m[pkg.PkgPath]; ok {
		return
	}
	m[pkg.PkgPath] = pkg
	for _, imp := range pkg.Imports {
		collectPackages(imp, m)
	}
}

func dedup(errors []discoveredError) []discoveredError {
	seen := map[string]bool{}
	var result []discoveredError
	for _, e := range errors {
		key := strconv.Itoa(e.Status) + "|" + e.Detail
		if !seen[key] {
			seen[key] = true
			result = append(result, e)
		}
	}
	return result
}

func generateFile(pkgName string, result map[string][]discoveredError) []byte {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by neoma-discover. DO NOT EDIT.\n")
	buf.WriteString("package " + pkgName + "\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/MeGaNeKoS/neoma/core\"\n")
	buf.WriteString("\t\"github.com/MeGaNeKoS/neoma/neoma\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("func init() {\n")
	buf.WriteString("\tneoma.RegisterDiscoveredErrors(map[string][]core.DiscoveredError{\n")

	names := make([]string, 0, len(result))
	for name := range result {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		errs := result[name]
		buf.WriteString("\t\t\"" + name + "\": {\n")
		for _, e := range errs {
			_, _ = fmt.Fprintf(&buf, "\t\t\t{Status: %d, Title: %q, Detail: %q},\n",
				e.Status, e.Title, e.Detail)
		}
		buf.WriteString("\t\t},\n")
	}

	buf.WriteString("\t})\n")
	buf.WriteString("}\n")

	return buf.Bytes()
}
